name: Phenopacket Store Toolkit CI

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main, develop ]

jobs:
    run-ci:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.12']

      steps:
        - uses: actions/checkout@v4
        - name: Initialize Python
          uses: actions/setup-python@v4.3.1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Phenopacket Store Toolkit with release and test dependencies
          run: |
            python3 -m pip install .[test,release]
        - name: Run tests
          run: |
            pytest
